"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob
import itertools
import os

from setuptools import setup

def find_data_files(*patterns):
    data_files = {}
    for fn in itertools.chain(*(glob.iglob(p) for p in patterns)):
        if os.path.isfile(fn):
            data_files.setdefault(os.path.dirname(fn), []).append(fn)
    return data_files.items()

DATA_FILES = find_data_files('images/*', 'nibs/*')
PACKAGES = ['qrcode', 'pymaging', 'pymaging-png']
MODULES = []#['python-qrcode']#['pymaging']
APP = ['src/QrCodeMenu.py']

print 'DATA_FILES', DATA_FILES
OPTIONS = { 'argv_emulation': False,
            'packages': PACKAGES,
            'includes': MODULES,
            'plist': {
                'LSUIElement': '1'
            }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    packages=['qrcode', 'pymaging', 'pymaging_png', 'qrcode.image'],
    package_dir={   '': 'src',
                    'qrcode': 'lib/python-qrcode/qrcode',
                    'qrcode.image': 'lib/python-qrcode/qrcode/image',
                    'pymaging': 'lib/pymaging/pymaging',
                    'pymaging_png': 'lib/pymaging-png/pymaging_png'
                    #'pymaging_png.png': 'lib/pymaging-png/pymaging_png/'
                    },
    py_modules=[]
)
